### ISSUE TITLE
issues of the inference code

### ISSUE THREAD

**Issue by littlewhitesea** [LiRunyi2001/OmniSSR#1]
Hi, this work is very interesting and thanks for releasing the code. However, I met with some issues of the inference code.

Following your provided inference command line, I tried to run "test_sr_val_ddpm_text_T_oldcanvas_TAN-OmniSSR-TAN.py". It reported one problem as follows:

![img1](https://github.com/user-attachments/assets/250ee701-ea95-4c7b-ae79-e76ec2384a96)

So I changed "sample_canvas_pano" to "sample_canvas". However, the other issue appeared.

![img2](https://github.com/user-attachments/assets/3697b924-c1d8-4c3e-9ee4-39593fa0c7ff)

Could you give me some suggestions to deal with this problem?

Thanks in advance.

**Comment by llstela** [comment]
> Hi, this work is very interesting and thanks for releasing the code. However, I met with some issues of the inference code.
> 
> Following your provided inference command line, I tried to run "test_sr_val_ddpm_text_T_oldcanvas_TAN-OmniSSR-TAN.py". It reported one problem as follows:
> 
> ![img1](https://private-user-images.githubusercontent.com/47802308/361196247-250ee701-ea95-4c7b-ae79-e76ec2384a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc1MzQsIm5iZiI6MTcyNTM3NzIzNCwicGF0aCI6Ii80NzgwMjMwOC8zNjExOTYyNDctMjUwZWU3MDEtZWE5NS00YzdiLWFlNzktZTc2ZWMyMzg0YTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MjcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MmU3ZTMyMTM1MDZiYzZlZTkzOGIyMGIyMTg0MmI2YTFiNGZjNzgyNWQzYmQyZWM3ZjAxZDNmMGJiM2FmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c8lt4E3LEN3eE3eCl-AaFFem6Cyj_llO2RuyudL0mlo)
> 
> So I changed "sample_canvas_pano" to "sample_canvas". However, the other issue appeared.
> 
> ![img2](https://private-user-images.githubusercontent.com/47802308/361196327-3697b924-c1d8-4c3e-9ee4-39593fa0c7ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc1MzQsIm5iZiI6MTcyNTM3NzIzNCwicGF0aCI6Ii80NzgwMjMwOC8zNjExOTYzMjctMzY5N2I5MjQtYzFkOC00YzNlLTllZTQtMzk1OTNmYTBjN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MjcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDIyMmJlMjlhMGEwMWMwNTQxMjU1OTdjMWIyMmVmNmJhOTljOWM0ZWE4MWFkODk1ZmYzYmJjYzM1N2YwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OjVuLqyhOKyaSB9oAvNeqM-ttaKIamlVvec8ExT-us4)
> 
> Could you give me some suggestions to deal with this problem?
> 
> Thanks in advance.

Thanks for your feedback. We will check the corresponding code soon.

**Comment by llstela** [comment]
> Hi, this work is very interesting and thanks for releasing the code. However, I met with some issues of the inference code.
> 
> Following your provided inference command line, I tried to run "test_sr_val_ddpm_text_T_oldcanvas_TAN-OmniSSR-TAN.py". It reported one problem as follows:
> 
> ![img1](https://private-user-images.githubusercontent.com/47802308/361196247-250ee701-ea95-4c7b-ae79-e76ec2384a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc5OTEsIm5iZiI6MTcyNTM3NzY5MSwicGF0aCI6Ii80NzgwMjMwOC8zNjExOTYyNDctMjUwZWU3MDEtZWE5NS00YzdiLWFlNzktZTc2ZWMyMzg0YTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMTBmZDBlMjI2ZmEwODA3MDk5OTllYjA5NTY5NzNjNjVjNzc1MjVlZDViMGE4YWZjNjlhMDhkMThkYmJhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wdWdyP539L0gcF2kEs7bFV0n_jxkWDV1cibr-1klNgQ)
> 
> So I changed "sample_canvas_pano" to "sample_canvas". However, the other issue appeared.
> 
> ![img2](https://private-user-images.githubusercontent.com/47802308/361196327-3697b924-c1d8-4c3e-9ee4-39593fa0c7ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc5OTEsIm5iZiI6MTcyNTM3NzY5MSwicGF0aCI6Ii80NzgwMjMwOC8zNjExOTYzMjctMzY5N2I5MjQtYzFkOC00YzNlLTllZTQtMzk1OTNmYTBjN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODQ4ZGI4MGY0NjdjZjFhNmQ4NzdhZmI2YzdhYWE2ZTdkNjBhM2Q1NTI3MDRlY2VhNTgwZGZlZTA0MWE0MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q7VBdSqBkymU3Dp6vkUZ1XlIHFwxQEQVJIsFlsgRWAE)
> 
> Could you give me some suggestions to deal with this problem?
> 
> Thanks in advance.

Please give me the complete command line used to run inference. I guess something is wrong with your configuration, maybe "**--config configs/stableSRNew/v2-finetune_text_T_512_pano.yaml**". As in _v2-finetune_text_T_512_pano.yaml_, we are using _LatentDiffusionSRTextWTPano_, _instead of LatentDiffusionSRTextWT_.

**Comment by littlewhitesea** [comment]
Many thanks for your reply. I checked the command line again. You are right, it's the problem of the configuration. Now, it can work. Thanks for your help again.
